name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Define .env file
              shell: bash
              run: |
                  touch .env
                  echo LINE_TOKEN=${{ secrets.LINE_TOKEN }} >> .env
                  echo PORT=${{ secrets.PORT }} >> .env
            - name: Define firebase config
              run: 'echo "$FIREBASE_CONFIG" > ./config/arsa-prompt-offical-firebase-adminsdk-aov6q-764569afd3.json'
              shell: bash
              env:
                  FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag arsa-prompt
            - name: Run container
              run: docker run -p 3002:3002 --rm -d --network backend --name arsa-prompt arsa-prompt
